// Run with Playwright available in NODE_PATH; uses only a disposable test DB.
const {chromium} = require('playwright');
const {spawn} = require('node:child_process');
const {once} = require('node:events');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
  const server=spawn(process.env.PYTHON||'python3',['-m','tests.miniapp_fixture'],{cwd:path.resolve(__dirname,'..'),stdio:['ignore','pipe','inherit']});
  let browser;
  try{
    const [chunk]=await once(server.stdout,'data');
    const {url,auth}=JSON.parse(chunk.toString());
    browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});
    const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.route('https://telegram.org/js/telegram-web-app.js',route=>route.fulfill({contentType:'text/javascript',body:`window.Telegram={WebApp:{initData:${JSON.stringify(auth)},colorScheme:'light',ready(){},expand(){},onEvent(){},BackButton:{show(){},hide(){},onClick(){}}}};`}));
    await page.goto(url);
    const click=async(name)=>page.getByRole('button',{name,exact:true}).click();
    const submit=async(name)=>{await page.getByRole('dialog').getByRole('button',{name,exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#modal').open);};
    await click('+ Новая');
    await page.getByLabel('Полная стоимость корта, ฿').fill('200');
    await submit('Создать тренировку');
    await page.getByRole('heading',{name:'02 · Участники'}).waitFor();
    for(const name of ['Настя','Андрей Н']){
      await click('+ Добавить');
      await page.getByLabel('Участник',{exact:true}).selectOption({label:name});
      await submit('Добавить');
    }
    await click('+ Добавить');
    await page.getByLabel('Участник',{exact:true}).selectOption('new');
    await page.getByLabel('Имя участника',{exact:true}).fill('Гость <тест>');
    await page.getByLabel('Сохранить для следующих тренировок').uncheck();
    await submit('Добавить');
    await page.locator('.person').filter({hasText:'Гость <тест>'}).getByRole('button',{name:'Изменить'}).click();
    await page.getByLabel('Время игры, ч').fill('1,5');
    await page.getByLabel('Потрачено воланов, шт.').fill('2');
    await page.getByLabel('Цена одного волана, ฿').fill('30');
    await submit('Сохранить');
    await page.locator('.person').filter({hasText:'Гость <тест>'}).getByRole('button',{name:'Изменить'}).click();
    await click('Убрать из тренировки');
    await submit('Убрать');
    await click('+ Плательщик');
    await page.getByLabel('Участник',{exact:true}).selectOption({label:'Настя'});
    await page.getByLabel('Оплачено за корт, ฿').fill('200');
    await submit('Сохранить');
    await page.locator('#notice').waitFor({state:'hidden'});
    await page.screenshot({path:'/tmp/bad-bot-miniapp-training.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await click('Посмотреть расчёт →');
    await submit('Зафиксировать расчёт');
    await click('Отметить оплату');
    await page.getByLabel('Полученная сумма, ฿').fill('40');
    await submit('Отметить оплату');
    await page.getByText('Получено 40 ฿ · остаток 60 ฿',{exact:true}).waitFor();
    await click('Отметить оплату');
    await click('Отменить последнюю отметку');
    await submit('Отменить отметку');
    await click('Отметить оплату');
    await submit('Отметить оплату');
    await click('Закрыть тренировку ✓');
    await submit('Закрыть тренировку');
    await click('Открыть тренировку снова');
    await page.getByText('Сбор оплат',{exact:true}).waitFor();
    await click('Опубликовать итог');
    await submit('Опубликовать');
    await click('← Тренировки');
    await page.locator('#notice').waitFor({state:'hidden'});
    await page.screenshot({path:'/tmp/bad-bot-miniapp-home.png',fullPage:true});
    await click('Справочники');
    await page.getByLabel('Поиск по имени').fill('zzzz');
    await page.getByText('Никого не нашли.',{exact:true}).waitFor();
    await click('Группа');
    await page.getByRole('heading',{name:'Snowflakes · Бадминтон'}).waitFor();
    await page.setViewportSize({width:1280,height:900});
    await click('Тренировки');
    await page.screenshot({path:'/tmp/bad-bot-miniapp-desktop.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.setViewportSize({width:320,height:740});
    await page.evaluate(()=>document.documentElement.dataset.theme='dark');
    await click('+ Новая');
    await page.getByLabel('Локация',{exact:true}).selectOption('new');
    await page.getByLabel('Название локации').fill('Новый зал');
    await page.getByLabel('Полная стоимость корта, ฿').fill('0');
    await page.screenshot({path:'/tmp/bad-bot-miniapp-dark.png',fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await submit('Создать тренировку');
    await page.getByRole('heading',{name:'Новый зал',exact:true}).waitFor();
    assert.deepEqual(errors,[]);
    console.log('Browser lifecycle passed at mobile and desktop widths. Screenshots: /tmp/bad-bot-miniapp-*.png');
  }finally{if(browser)await browser.close();server.kill();}
})().catch(error=>{console.error(error);process.exitCode=1;});
